{"name": "Удаление курьера, по id не существующего курьера, не успешно", "status": "passed", "start": 1712509250647, "stop": 1712509251204, "uuid": "7063046d-a2a9-49a2-a684-d3bfd537b39f", "historyId": "80a5525c0b37e3738137c5911e8a89db", "testCaseId": "80a5525c0b37e3738137c5911e8a89db", "fullName": "tests.couriers.test_delete_courier.TestDeleteCourier#test_delete_courier_with_not_existing_courier_id_fail", "labels": [{"name": "parentSuite", "value": "tests.couriers"}, {"name": "suite", "value": "test_delete_courier"}, {"name": "subSuite", "value": "TestDeleteCourier"}, {"name": "host", "value": "DESKTOP-HCED1QB"}, {"name": "thread", "value": "35896-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.couriers.test_delete_courier"}]}