{"name": "Принять заказ. Если НЕ передан id заказа и передан id курьера, НЕ успешно", "status": "failed", "statusDetails": {"message": "AssertionError: assert 404 == 400\n +  where 404 = <Response [404]>.status_code", "trace": "self = <tests.orders.test_accept_order.TestAcceptOrder object at 0x000002B12DE06F00>\ncourier_login_valid_creds = ({'firstName': '37ze50l67q', 'login': 'dtv5h8628h', 'password': '7wov5cnh88'}, 289732)\n\n    @allure.title('Принять заказ. Если НЕ передан id заказа и передан id курьера, НЕ успешно')\n    def test_accept_order_with_empty_order_id_fail(\n            self,\n            courier_login_valid_creds,\n    ):\n        courier_id = courier_login_valid_creds[1]\n        order_helpers = OrderHelpers()\n        resp = order_helpers.accept_order(\n            None,\n            courier_id,\n        )\n>       assert resp.status_code == 400\nE       assert 404 == 400\nE        +  where 404 = <Response [404]>.status_code\n\ntests\\orders\\test_accept_order.py:52: AssertionError"}, "steps": [{"name": "Принять заказ с id None курьером с courier_id 289732", "status": "passed", "parameters": [{"name": "order_id", "value": "None"}, {"name": "courier_id", "value": "289732"}], "start": 1712769139006, "stop": 1712769139306}], "start": 1712769139006, "stop": 1712769139306, "uuid": "cef0545d-0537-4622-ab1d-56c7d229e029", "historyId": "415d6c569ef8bcfc87ae2de00af7174c", "testCaseId": "415d6c569ef8bcfc87ae2de00af7174c", "fullName": "tests.orders.test_accept_order.TestAcceptOrder#test_accept_order_with_empty_order_id_fail", "labels": [{"name": "parentSuite", "value": "tests.orders"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "DESKTOP-HCED1QB"}, {"name": "thread", "value": "4340-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.orders.test_accept_order"}]}