{"name": "Принять заказ. Если НЕ передан id заказа и передан id курьера, НЕ успешно", "status": "failed", "statusDetails": {"message": "AssertionError: assert 404 == 400\n +  where 404 = <Response [404]>.status_code", "trace": "self = <tests.orders.test_accept_order.TestAcceptOrder object at 0x0000020AFB847200>\ncourier_login_valid_creds = ({'firstName': '7pt8l2ama6', 'login': 'frsygal7wa', 'password': '8y4e7ptuyk'}, 289772)\n\n    @allure.title('Принять заказ. Если НЕ передан id заказа и передан id курьера, НЕ успешно')\n    def test_accept_order_with_empty_order_id_fail(\n            self,\n            courier_login_valid_creds,\n    ):\n        courier_id = courier_login_valid_creds[1]\n        order_helpers = OrderHelpers()\n        resp = order_helpers.accept_order(\n            None,\n            courier_id,\n        )\n>       assert resp.status_code == 400\nE       assert 404 == 400\nE        +  where 404 = <Response [404]>.status_code\n\ntests\\orders\\test_accept_order.py:52: AssertionError"}, "steps": [{"name": "Принять заказ с id None курьером с courier_id 289772", "status": "passed", "parameters": [{"name": "order_id", "value": "None"}, {"name": "courier_id", "value": "289772"}], "start": 1712770938136, "stop": 1712770938434}], "start": 1712770938136, "stop": 1712770938435, "uuid": "96b63243-5785-48ee-a67e-927102621918", "historyId": "415d6c569ef8bcfc87ae2de00af7174c", "testCaseId": "415d6c569ef8bcfc87ae2de00af7174c", "fullName": "tests.orders.test_accept_order.TestAcceptOrder#test_accept_order_with_empty_order_id_fail", "labels": [{"name": "parentSuite", "value": "tests.orders"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "DESKTOP-HCED1QB"}, {"name": "thread", "value": "13164-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.orders.test_accept_order"}]}